### ISSUE TITLE
Trouble Implementing replay_salt Retrieval in a Microservice Using dota2-user Library

### ISSUE THREAD

**Issue by hunterxp** [itsjfx/node-dota2-user#10]
Hello Thomas,

Firstly, I'd like to extend my gratitude for developing the `dota2-user` library. It's a promising tool that seems user-friendly and straightforward.

I'm currently working on implementing a microservice using your library. Its main function is to retrieve the `replay_salt` for a given match. Unfortunately, I've encountered some issues where the service doesn't work as expected.

Here's the scenario I'm struggling with:

1. I set up an Express server to handle a GET request to fetch the `replay_salt` for a specific `matchId`.
2. Upon receiving a request, the server sends a message to the Dota 2 Game Coordinator to retrieve the match details.
3. I am expecting to receive a `replay_salt` in response, which I can then send back to the client.

However, the call to the Game Coordinator does not seem to be yielding a response, and the server times out waiting for the `k_EMsgGCMatchDetailsResponse`. The same `matchId` works fine when I use it directly in the example code provided in the library documentation, so I'm quite puzzled about what might be going wrong when it's adapted into my server setup.

I'm attaching the server code below for your reference:

```javascript
require('dotenv').config();

const express = require('express');
const SteamUser = require('steam-user');
const { Dota2User } = require('dota2-user');
const { EDOTAGCMsg } = require('dota2-user/protobufs');

const app = express();
const client = new SteamUser();
const dota2 = new Dota2User(client);

app.use(express.json());

const logOnOptions = {
	accountName: process.env.STEAM_ACCOUNT_NAME,
	password: process.env.STEAM_PASSWORD,
	twoFactorCode: process.env.STEAM_TWO_FACTOR_CODE,
};

client.logOn(logOnOptions);

client.on('loggedOn', () => {
	console.log('Logged into Steam');
	client.setPersona(SteamUser.EPersonaState.Online);
});

client.on('error', (e) => {
	console.error('Steam error:', e);
});

app.get('/getReplaySalt/:matchId', (req, res) => {
	const matchId = req.params.matchId;
	console.log(`Received request for match ID: ${matchId}`);

	dota2.send(EDOTAGCMsg.k_EMsgGCMatchDetailsRequest, { matchId: Number(matchId) });

	dota2.once(EDOTAGCMsg.k_EMsgGCMatchDetailsResponse, (data) => {
		console.log(`Received response for match ID: ${matchId}`);
		if (data.match) {
			console.log(`Match data found for match ID: ${matchId}`);
			res.json({ replaySalt: data.match.replaySalt });
		} else {
			console.log(`No match data found for match ID: ${matchId}`);
			res.status(404).send('Match data not found');
		}
	});

	dota2.once('disconnectedFromGC', () => {
		console.log('Disconnected from Game Coordinator');
		res.status(503).send('Disconnected from Game Coordinator');
	});
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
	console.log(`Server is running on port ${PORT}`);
});
```

The environment is consistent with the example: Node.js version, same library versions, etc. I made sure to follow the library's usage patterns as closely as possible.

Could you offer any insights or suggestions on what might be causing this issue or where I might be going wrong? Any help would be greatly appreciated.

Thank you for your time and assistance.

Best regards,

**Comment by itsjfx** [comment]
Hi there,

Apologies on the delay in getting back to you, I was away from technology for a few days :)

There were a few small things missing from your code:
* you need to launch the Dota 2 app yourself before the library will establish a connection to the GC:
    * <https://github.com/itsjfx/node-dota2-user/blob/2c70c62c3dac99104455123896410bc754baa1ae/examples/get-match-details.ts#L20-L21>
* your `.once` call was on the base `dota2` class `EventEmitter`, and not on `dota2.router` class `EventEmitter`
    * i know that my choice of two emitters is not the most friendly and that it can rightly be confusing at first glance
    * <https://github.com/itsjfx/node-dota2-user/blob/2c70c62c3dac99104455123896410bc754baa1ae/examples/get-match-details.ts#L29>


I believe the below snippet will do what you want as a minimum:

```js
require('dotenv').config();

const express = require('express');
const SteamUser = require('steam-user');
const { Dota2User } = require('dota2-user');
const { EDOTAGCMsg } = require('dota2-user/protobufs');

const app = express();
const client = new SteamUser();
const dota2 = new Dota2User(client);

app.use(express.json());

const logOnOptions = {
	accountName: process.env.STEAM_ACCOUNT_NAME,
	password: process.env.STEAM_PASSWORD,
	twoFactorCode: process.env.STEAM_TWO_FACTOR_CODE,
};

client.logOn(logOnOptions);

client.on('loggedOn', () => {
	console.log('Logged into Steam');
	client.setPersona(SteamUser.EPersonaState.Online);
	client.gamesPlayed(Dota2User.STEAM_APPID);
});

client.on('error', (e) => {
	console.error('Steam error:', e);
});

dota2.on('connectedToGC', () => {
    console.log('Connected to GC');
});

app.get('/getReplaySalt/:matchId', (req, res) => {
	const matchId = req.params.matchId;
	console.log(`Received request for match ID: ${matchId}`);

	dota2.send(EDOTAGCMsg.k_EMsgGCMatchDetailsRequest, { matchId: Number(matchId) });

	dota2.router.once(EDOTAGCMsg.k_EMsgGCMatchDetailsResponse, (data) => {
		console.log(`Received response for match ID: ${matchId}`);
		if (data.match) {
			console.log(`Match data found for match ID: ${matchId}`);
			res.json({ replaySalt: data.match.replaySalt });
		} else {
			console.log(`No match data found for match ID: ${matchId}`);
			res.status(404).send('Match data not found');
		}
	});
});

dota2.on('disconnectedFromGC', () => {
    console.log('Disconnected from Game Coordinator');
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
	console.log(`Server is running on port ${PORT}`);
});
```

Beware that this isn't very robust.
There's no error handing for whether the bot is logged in or has a GC session, and the `dota2.router.once` will face a race condition at some stage if there's multiple requests.

You can solve the potential race condition by having an `.on()` that listens for messages, keeps track of state, and calls the `express` callback (or resolves a promise/callback) when a matching message comes in.

Another option I'm exploring is "job" based messages which can be sent to the Dota 2 GC -- but not every message supports this mechanism. It may help this specific message if it supports a job based message flow. This is not currently implemented, so it's not possible for you to try right now. 

Anyhow, hope the above is helpful and enough to get you started.
Thank you for your patience and willingness to use the module!
If you have anymore queries feel free to ask.

**Comment by hunterxp** [comment]
Hey! It works! 🎉 
Thank you very much for your help! 🤗🤝
