### ISSUE TITLE
does it support stream ?

### ISSUE THREAD

**Issue by Un1xCr3wR0x** [itsjfx/node-dota2-user#11]
@itsjfx i wanna start watching some live matches based on the current live matches is it possible ?
and 1 more thing how can i see the launched game client ?

**Comment by Un1xCr3wR0x** [comment]
and iam trying 

to use this get all live matches 
```
    dota2.on('connectedToGC', () => {
        dota2.send(EDOTAGCMsg.k_EMsgGCToGCGetLiveLeagueMatches);
    });
```

but iam getting 
```
Expected 2 arguments, but got 1.ts(2554)
Dota2User.d.ts(22, 61): An argument for 'body' was not provided.
(enum member) EDOTAGCMsg.k_EMsgGCToGCGetLiveLeagueMatches = 7631
```

**Comment by Un1xCr3wR0x** [comment]
any updates ? @itsjfx

**Comment by itsjfx** [comment]
hey @Un1xCr3wR0x , what are you after specifically? do you want to see top matches that get shown in the game client? or do you want to get information about a specific live match id?

**Comment by Un1xCr3wR0x** [comment]
i wanna get all top live matches 
then i wanna start streaming to twitch 
and give the viewers the ability to choose the game they wanna watch

**Comment by itsjfx** [comment]
I believe you can progamatically get the list of top games with this module, and then using a mixture of this module and public APIs extract information about the games. However you cannot use this module to "watch games". I don't provide support for the relays implementation to live spectate games to get data live.

This module does not actually launch a game client, instead it communicates to the Dota 2 game servers progamatically and acts like a real client. There is no client other than API calls the module makes for you, and that you make with the module. So there's no way to spectate a game live with this module like you can within the game.

**Comment by Un1xCr3wR0x** [comment]
aha ok thanks.
