### ISSUE TITLE
hello i just want to thank u again

### ISSUE THREAD

**Issue by Un1xCr3wR0x** [itsjfx/node-dota2-user#12]
thanks a lot for the GREATE WORK , u are amazing tbh

and i have 1 more question what if iam creating new account and i need to go throw this account with ur code and select i have played dota before and start searching for 10 secs then join guild and close the game does ur library support all of that ?

**Comment by itsjfx** [comment]
I _believe_ this is all possible, but I've not actually checked...

You can see which messages get sent to the GC if you check the game console, or by using [NetHook2](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2)
Once you have some data, you should be able to map them back to the protobufs, and send them in your TypeScript/JavaScript

**Comment by Un1xCr3wR0x** [comment]
can u explain more please ?

**Comment by Un1xCr3wR0x** [comment]
i just need to use it with typescript is it possible ?

**Comment by itsjfx** [comment]
I'm not 100% sure but I'd say it's likely you can do it.

This module makes it easier for you to talk to the Dota 2 GC with TypeScript, but you need to know which calls/messages to send. If you use the tool linked above, you can attempt to get message extracts, see if the game client makes these calls, and then make these calls yourself in TypeScript.

**Comment by Un1xCr3wR0x** [comment]
@itsjfx  hey , its me again sorry about my stupid questions but if i have lua script that will move the player to point in the map 
and i wanna hook this lua script into dota 2 when the game starts 
how can i do that ?

another question i have sandboxie machines i wanna use this lua script to move to diffrent spot is it possible ?
