### ISSUE TITLE
Please add a method to get the list of current live matches

### ISSUE THREAD

**Issue by eremenko1** [itsjfx/node-dota2-user#14]
Hi, I just want to say thank you so much for such a nice package! It is very cool to see that you are developing this direction.

I would like to ask you to add a method to get the list of current live matches (sourceTVGamesData), with the ability to filter by league ID, or hero ID (with page pagination). 

Or give instructions on how to add the necessary protobuffs yourself. Thank you!

**Comment by Ahafonov-mykyta** [comment]
Thank you for the amazing work on this package! 

I’d like to support the suggestion to add a method for retrieving live matches . It would be a fantastic and valuable addition.
Keep up the great work!

**Comment by itsjfx** [comment]
Hi, can you try [version 2.0.3](https://github.com/itsjfx/node-dota2-user/releases/tag/v2.0.3) and the example here: https://github.com/itsjfx/node-dota2-user/blob/master/examples/get-live-matches.ts

I've not checked what happens in the client as I need to reinstall the game, but based on your description this seems like the correct call.

**Comment by itsjfx** [comment]
May also expose a heroes enum in the module for quality of life. If you can find a reliable source for them let me know.

**Comment by eremenko1** [comment]
Wow, thank you so much, this is exactly what I needed!

There is one more request, is it possible to return the names of all fields as they are in other game-coordinators, or as in web-api. Not by camel-case, but also as in the original. 

This would make it easier to switch from another package, and also wouldn't need to write an adapter.

**Example of a response from your package:**
<img width="524" alt="image" src="https://github.com/user-attachments/assets/555d949f-c107-4b0b-be13-6ed753dc4e15" />

Example response from the official web-api of steam (same in all other game-coordinators):
<img width="350" alt="image" src="https://github.com/user-attachments/assets/d291b560-f041-4903-a2d8-870d2c59c60f" />

Or if you want the data to remain in the camel-case, it would be cool to specify the type of returned fields as a parameter.

For example like this:
//client, returnStyle = “camelCase” | “snakeCase”
const dota2 = new Dota2User(client, “snakeCase”);

Thanks for understanding!)

**Comment by itsjfx** [comment]
This may be possible with the protobuf library I use. Do you only want snake cases on returned values? Would you also need them when sending messages?

**Comment by eremenko1** [comment]
Hello. ✌️
It would be cool if such a style was like in the original API, that is, both requests and responses. Thank you

**Comment by itsjfx** [comment]
Hi,

I took a look into this. While it's possible to do support casing with my protobuf library via generated code and get snake typing working with some hacks, the libraries internals rely on the Router and send methods -- so it's not easy to do this cleanly

I need to refactor the code to protect the internal routing and sending mechanisms, so I'm not looking to implement this at the moment.

I understand why this would be useful though. You could use https://github.com/kbrabrand/snakify-ts -- it won't be as good as the pre-generated code from the protobuf library, but it'll do what you need

**Comment by eremenko1** [comment]
Hi, got it, thanks for the reply!
