### ISSUE TITLE
Thanks for the great work.

### ISSUE THREAD

**Issue by Svenmax** [itsjfx/node-dota2-user#4]
Nice job.

**Comment by itsjfx** [comment]
Thanks ! Please continue giving feedback and suggestions 👍

**Comment by Svenmax** [comment]
I'm not very good at programming, I don't know if your project can be a plug-in for the emulator below, so that it can play dota2 offline.
https://gitlab.com/Mr_Goldberg/goldberg_emulator

**Comment by itsjfx** [comment]
Hey, I don't believe my module is what you need to do this.

You can think of this module as a NodeJS/TypeScript Dota 2 **client** that you can control programmatically to do things (e.g. pull match and profile data, create lobbies, and what not). It does this by communicating to the real "game coordinator" or Dota 2 server.

What you likely need is something that emulates the Dota 2 game coordinator / **server**. I don't believe anything like this exists.

**Comment by Svenmax** [comment]
thanks for the reply. Such a project exists, but I don't know how to use it.
https://github.com/Hackerprod/-SKYNET-Steam-Emulator

**Comment by Svenmax** [comment]
https://filetransfer.io/data-package/CLTcfcfl#link

**Comment by itsjfx** [comment]
I still believe I can't help you out with your problem. I suggest reaching out to the people maintaining the project you linked above.

I do have [some notes](https://github.com/itsjfx/node-dota2-user/blob/master/docs/steam-interaction.md) on how the GC interaction works if you'd like some pointers.
