### ISSUE TITLE
custom game(arcade)

### ISSUE THREAD

**Issue by lintangtimur** [itsjfx/node-dota2-user#8]
Can this provide things like:

-Creating custom game lobbies?
-Detecting chat in custom game lobbies or during the in-game custom play?

based on go-dota2 paralin, i cant find documentation how to use that library
```
GC session state management
 Player profile fetching / call tracking
 SOCache tracking / state management
 Basic chat interaction
 Lobby tracking / state management
 Read lobby state correctly
 Implement normal lobby operations
 Party tracking / state management
 Read party and invite state correctly
 Implement normal party operations
 Code generation for API
 Code generation for events
 ```

**Comment by itsjfx** [comment]
Hey

> Creating custom game lobbies?

This should be possible, although I haven't tried yet. I believe it's possible cause [it seemed to be possible with node-dota2](https://github.com/Arcana/node-dota2/issues/657).
I'll try test this out.

>Detecting chat in custom game lobbies or during the in-game custom play?

Again I've not tried, but I believe detecting chat in custom game lobbies should be possible. As the bot cannot join games, I don't believe it's possible to detect chat in-game.
