### ISSUE TITLE
Abnormal CPU Resource Usage

### ISSUE THREAD

**Issue by LInkerH** [itsjfx/node-dota2-user#9]
When I run the file in the example, the CPU usage remains at full load, even if I stop the program, it has no effect, and I have to close my IDE.

IDEA version : IntelliJ IDEA 2023.1.4
CPU: I7-8700

**Comment by itsjfx** [comment]
Hi there, at the moment I rely on a lot of type inference, utility types, and some "hacky" ways to accomplish the strict type-ness of the module. I suspect this may be causing performance issues with your IDE.

I'll see if I can address these issues, although I'm somewhat held at the will of the module I use for generating TypeScript code out of protobufs.

Thank you for the report.
